# Generated by Django 5.2.7 on 2025-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна (грн)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tool_type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вага (кг)'),
        ),
    ]
