# Generated by Django 5.2.7 on 2025-11-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_app', '0002_alter_product_brand_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Інструмент', 'verbose_name_plural': 'Інструменти'},
        ),
    ]
